plugins:
  - uses:
      - plugin: https://ubiquity-os-command-wallet-main.ubiquity.workers.dev
  - uses:
      - plugin: https://ubiquity-os-command-query-user-main.ubiquity.workers.dev
        with:
          allowPublicQuery: true
  - uses:
      - plugin: https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev
        with:
          labels:
            time:
              - "Time: <15 Minutes"
              - "Time: <1 Hour"
              - "Time: <2 Hours"
              - "Time: <4 Hours"
              - "Time: <1 Day"
              - "Time: <1 Week"
              - "Time: <1 Month"
            priority:
              - "Priority: 1 (Normal)"
              - "Priority: 2 (Medium)"
              - "Priority: 3 (High)"
              - "Priority: 4 (Urgent)"
              - "Priority: 5 (Emergency)"
          basePriceMultiplier: 2
          publicAccessControl:
            setLabel: true
            fundExternalClosedIssue: false
  - skipBotEvents: false
    uses:
      - plugin: ubiquity-os-marketplace/text-conversation-rewards@main
        # we don't skip bot events so conversation rewards triggered by the bot also run
        with:
          evmNetworkId: 100
          evmPrivateEncrypted: "bd5AFnSCO6c5jJyPifpOfr5Zys29RE7SyXkEU3akT13RtGmYDrqGIGuvJQyH53HA5dIba7PL5bXfll0JebmwXYe5gHIXSGX80WuGMDHh0cFfeGjHhmUXe8kkZ1OT2De9qRpqejJcEzdfi-8XNAvP7cQu2Vt-7RNnPw" # https://github.com/ubiquibot/conversation-rewards/pull/111#issuecomment-2348639931
          erc20RewardToken: "0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068"
          incentives:
            contentEvaluator:
              enabled: true
            userExtractor:
              enabled: true
              redeemTask: true
            dataPurge:
              enabled: true
            formattingEvaluator:
              multipliers:
                - role: [ISSUE_SPECIFICATION]
                  multiplier: 3
                  rewards:
                    wordValue: 0.1
                - role: [ISSUE_AUTHOR]
                  multiplier: 1
                  rewards:
                    wordValue: 0.2
                - role: [ISSUE_ASSIGNEE]
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                - role: [ISSUE_COLLABORATOR]
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                - role: [ISSUE_CONTRIBUTOR]
                  multiplier: 0.25
                  rewards:
                    wordValue: 0.1
                - role: [PULL_SPECIFICATION]
                  multiplier: 0
                  rewards:
                    wordValue: 0
                - role: [PULL_AUTHOR]
                  multiplier: 0
                  rewards:
                    wordValue: 0.2
                - role: [PULL_ASSIGNEE]
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                - role: [PULL_COLLABORATOR]
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                - role: [PULL_CONTRIBUTOR]
                  multiplier: 0.25
                  rewards:
                    wordValue: 0.1
            permitGeneration:
              enabled: true
            githubComment:
              post: true
              debug: false
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-disqualifier@main
        with:
          watch:
            optOut:
              - ubiquibot
              - launch-party
              - staging
              - production
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-merging@main
        with:
          approvalsRequired:
            collaborator: 1
          mergeTimeout:
            collaborator: "3.5 days"
          repos:
            ignore:
              - ubiquibot
              - launch-party
              - staging
              - production
  - uses:
      - plugin: https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev
        with:
          reviewDelayTolerance: "3 Days"
          taskStaleTimeoutDuration: "30 Days"
          startRequiresWallet: true # default is true
          requiredLabelsToStart: ["Priority: 3 (High)", "Priority: 4 (Urgent)", "Priority: 5 (Emergency)"]
  - uses:
      - plugin: ubiquity-os-marketplace/text-vector-embeddings@main
